CREATE SCHEMA app;

CREATE TABLE app.schema_migrations (
  version varchar(128) PRIMARY KEY,
  checksum char(64) NOT NULL,
  applied_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT schema_migrations_checksum_format_chk
    CHECK (checksum ~ '^[0-9a-f]{64}$')
);

CREATE TABLE app.import_runs (
  id uuid PRIMARY KEY,
  source_sha256 char(64) NOT NULL,
  source_label varchar(160) NOT NULL,
  importer_version varchar(64) NOT NULL,
  mode varchar(16) NOT NULL,
  status varchar(24) NOT NULL,
  source_counts jsonb NOT NULL DEFAULT '{}'::jsonb,
  imported_counts jsonb NOT NULL DEFAULT '{}'::jsonb,
  checksum_summary jsonb NOT NULL DEFAULT '{}'::jsonb,
  started_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at timestamptz,
  CONSTRAINT import_runs_source_sha256_uq UNIQUE (source_sha256),
  CONSTRAINT import_runs_source_sha256_format_chk
    CHECK (source_sha256 ~ '^[0-9a-f]{64}$'),
  CONSTRAINT import_runs_mode_chk
    CHECK (mode IN ('dry_run', 'staging', 'final')),
  CONSTRAINT import_runs_status_chk
    CHECK (status IN ('running', 'passed', 'blocked', 'failed')),
  CONSTRAINT import_runs_completed_at_chk
    CHECK (completed_at IS NULL OR completed_at >= started_at)
);

CREATE TABLE app.import_anomalies (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  import_run_id uuid NOT NULL,
  severity varchar(16) NOT NULL,
  category varchar(80) NOT NULL,
  entity_type varchar(80) NOT NULL,
  legacy_reference_hash varchar(32),
  field_name varchar(120),
  candidate_count integer NOT NULL DEFAULT 0,
  blocking boolean NOT NULL DEFAULT true,
  detail jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT import_anomalies_import_run_fk
    FOREIGN KEY (import_run_id) REFERENCES app.import_runs (id) ON DELETE RESTRICT,
  CONSTRAINT import_anomalies_severity_chk
    CHECK (severity IN ('info', 'warning', 'error')),
  CONSTRAINT import_anomalies_candidate_count_chk
    CHECK (candidate_count >= 0)
);

CREATE INDEX import_anomalies_run_blocking_idx
  ON app.import_anomalies (import_run_id, blocking, severity);

CREATE TABLE app.accounts (
  id varchar(32) PRIMARY KEY,
  status varchar(24) NOT NULL,
  display_name varchar(120) NOT NULL DEFAULT '',
  avatar_url text NOT NULL DEFAULT '',
  created_from varchar(32) NOT NULL,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  CONSTRAINT accounts_id_nonempty_chk CHECK (btrim(id) <> ''),
  CONSTRAINT accounts_status_chk CHECK (status IN ('active', 'disabled', 'closed')),
  CONSTRAINT accounts_created_from_chk
    CHECK (created_from IN ('web_phone', 'miniapp_openid', 'migration', 'admin_repair')),
  CONSTRAINT accounts_updated_at_chk CHECK (updated_at >= created_at)
);

CREATE INDEX accounts_status_idx ON app.accounts (status);
CREATE INDEX accounts_created_at_idx ON app.accounts (created_at);

CREATE TABLE app.users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_id text,
  account_id varchar(32) NOT NULL,
  phone varchar(32),
  openid varchar(160),
  unionid varchar(160),
  source varchar(32) NOT NULL,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  CONSTRAINT users_legacy_id_uq UNIQUE (legacy_id),
  CONSTRAINT users_account_fk
    FOREIGN KEY (account_id) REFERENCES app.accounts (id) ON DELETE RESTRICT,
  CONSTRAINT users_identity_present_chk
    CHECK (phone IS NOT NULL OR openid IS NOT NULL OR unionid IS NOT NULL),
  CONSTRAINT users_phone_nonempty_chk CHECK (phone IS NULL OR btrim(phone) <> ''),
  CONSTRAINT users_openid_nonempty_chk CHECK (openid IS NULL OR btrim(openid) <> ''),
  CONSTRAINT users_unionid_nonempty_chk CHECK (unionid IS NULL OR btrim(unionid) <> ''),
  CONSTRAINT users_source_chk
    CHECK (source IN ('web', 'miniapp', 'web+miniapp', 'migration')),
  CONSTRAINT users_updated_at_chk CHECK (updated_at >= created_at)
);

CREATE INDEX users_account_id_idx ON app.users (account_id);
CREATE UNIQUE INDEX users_phone_uq
  ON app.users (phone) WHERE phone IS NOT NULL;
CREATE UNIQUE INDEX users_openid_uq
  ON app.users (openid) WHERE openid IS NOT NULL;
CREATE INDEX users_unionid_idx
  ON app.users (unionid) WHERE unionid IS NOT NULL;

CREATE TABLE app.operators (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_id text,
  username varchar(120) NOT NULL,
  password_hash text NOT NULL,
  role varchar(24) NOT NULL,
  name varchar(120) NOT NULL DEFAULT '',
  enabled boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  CONSTRAINT operators_legacy_id_uq UNIQUE (legacy_id),
  CONSTRAINT operators_username_uq UNIQUE (username),
  CONSTRAINT operators_username_nonempty_chk CHECK (btrim(username) <> ''),
  CONSTRAINT operators_password_hash_nonempty_chk CHECK (btrim(password_hash) <> ''),
  CONSTRAINT operators_role_chk CHECK (role IN ('admin', 'qc')),
  CONSTRAINT operators_updated_at_chk CHECK (updated_at >= created_at)
);

CREATE INDEX operators_role_enabled_idx ON app.operators (role, enabled);

CREATE TABLE app.qr_batches (
  id text PRIMARY KEY,
  name varchar(160) NOT NULL,
  brand_name varchar(160) NOT NULL DEFAULT '',
  note text NOT NULL DEFAULT '',
  disclosure_text text NOT NULL DEFAULT '',
  show_brand_disclosure_default boolean NOT NULL DEFAULT false,
  created_by_operator_id bigint,
  created_by_snapshot varchar(120) NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  CONSTRAINT qr_batches_id_nonempty_chk CHECK (btrim(id) <> ''),
  CONSTRAINT qr_batches_name_nonempty_chk CHECK (btrim(name) <> ''),
  CONSTRAINT qr_batches_creator_fk
    FOREIGN KEY (created_by_operator_id) REFERENCES app.operators (id) ON DELETE RESTRICT,
  CONSTRAINT qr_batches_updated_at_chk CHECK (updated_at >= created_at)
);

CREATE INDEX qr_batches_created_at_idx ON app.qr_batches (created_at);

CREATE TABLE app.qr_codes (
  id text PRIMARY KEY,
  issue_status varchar(24) NOT NULL,
  lifecycle_status varchar(24) NOT NULL,
  hidden boolean NOT NULL DEFAULT false,
  batch_id text,
  print_batch_id text,
  qr_image_url_snapshot text NOT NULL DEFAULT '',
  access_token varchar(255),
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  CONSTRAINT qr_codes_id_nonempty_chk CHECK (btrim(id) <> ''),
  CONSTRAINT qr_codes_issue_status_chk CHECK (issue_status IN ('unissued', 'issued')),
  CONSTRAINT qr_codes_lifecycle_status_chk
    CHECK (lifecycle_status IN ('unactivated', 'co_creating', 'activated')),
  CONSTRAINT qr_codes_batch_fk
    FOREIGN KEY (batch_id) REFERENCES app.qr_batches (id) ON DELETE RESTRICT,
  CONSTRAINT qr_codes_access_token_nonempty_chk
    CHECK (access_token IS NULL OR btrim(access_token) <> ''),
  CONSTRAINT qr_codes_updated_at_chk CHECK (updated_at >= created_at)
);

CREATE UNIQUE INDEX qr_codes_access_token_uq
  ON app.qr_codes (access_token) WHERE access_token IS NOT NULL;
CREATE INDEX qr_codes_batch_id_idx ON app.qr_codes (batch_id);
CREATE INDEX qr_codes_lifecycle_status_idx ON app.qr_codes (lifecycle_status);
CREATE INDEX qr_codes_issue_lifecycle_idx ON app.qr_codes (issue_status, lifecycle_status);
CREATE INDEX qr_codes_hidden_idx ON app.qr_codes (hidden);
CREATE INDEX qr_codes_created_at_idx ON app.qr_codes (created_at);

CREATE TABLE app.records (
  qr_id text PRIMARY KEY,
  account_id varchar(32) NOT NULL,
  content text NOT NULL DEFAULT '',
  image_url_snapshot text NOT NULL DEFAULT '',
  image_object_key text,
  image_sha256 char(64),
  phone_snapshot varchar(32) NOT NULL DEFAULT '',
  sealed_at timestamptz,
  show_brand_disclosure boolean NOT NULL DEFAULT false,
  brand_disclosure_text_snapshot text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  CONSTRAINT records_qr_fk
    FOREIGN KEY (qr_id) REFERENCES app.qr_codes (id) ON DELETE RESTRICT,
  CONSTRAINT records_account_fk
    FOREIGN KEY (account_id) REFERENCES app.accounts (id) ON DELETE RESTRICT,
  CONSTRAINT records_image_sha256_format_chk
    CHECK (image_sha256 IS NULL OR image_sha256 ~ '^[0-9a-f]{64}$'),
  CONSTRAINT records_updated_at_chk CHECK (updated_at >= created_at),
  CONSTRAINT records_sealed_at_chk CHECK (sealed_at IS NULL OR sealed_at >= created_at)
);

CREATE INDEX records_account_sealed_idx ON app.records (account_id, sealed_at DESC);
CREATE INDEX records_sealed_at_idx ON app.records (sealed_at);
CREATE INDEX records_image_object_key_idx
  ON app.records (image_object_key) WHERE image_object_key IS NOT NULL;

CREATE TABLE app.co_creations (
  id uuid PRIMARY KEY,
  qr_id text NOT NULL,
  owner_account_id varchar(32) NOT NULL,
  owner_phone_snapshot varchar(32) NOT NULL DEFAULT '',
  status varchar(24) NOT NULL,
  started_at timestamptz NOT NULL,
  finalized_at timestamptz,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  CONSTRAINT co_creations_qr_uq UNIQUE (qr_id),
  CONSTRAINT co_creations_qr_fk
    FOREIGN KEY (qr_id) REFERENCES app.qr_codes (id) ON DELETE RESTRICT,
  CONSTRAINT co_creations_owner_account_fk
    FOREIGN KEY (owner_account_id) REFERENCES app.accounts (id) ON DELETE RESTRICT,
  CONSTRAINT co_creations_status_chk CHECK (status IN ('active', 'finalized', 'closed')),
  CONSTRAINT co_creations_finalized_at_chk
    CHECK (finalized_at IS NULL OR finalized_at >= started_at),
  CONSTRAINT co_creations_updated_at_chk CHECK (updated_at >= created_at)
);

CREATE INDEX co_creations_owner_status_idx
  ON app.co_creations (owner_account_id, status);
CREATE INDEX co_creations_status_started_idx
  ON app.co_creations (status, started_at);

CREATE TABLE app.co_creation_comments (
  id uuid PRIMARY KEY,
  co_creation_id uuid NOT NULL,
  account_id varchar(32) NOT NULL,
  legacy_comment_id text,
  phone_snapshot varchar(32) NOT NULL DEFAULT '',
  author_name varchar(120) NOT NULL DEFAULT '',
  content text NOT NULL,
  status varchar(16) NOT NULL,
  created_at timestamptz NOT NULL,
  deleted_at timestamptz,
  CONSTRAINT co_creation_comments_creation_fk
    FOREIGN KEY (co_creation_id) REFERENCES app.co_creations (id) ON DELETE RESTRICT,
  CONSTRAINT co_creation_comments_account_fk
    FOREIGN KEY (account_id) REFERENCES app.accounts (id) ON DELETE RESTRICT,
  CONSTRAINT co_creation_comments_legacy_scope_uq
    UNIQUE (co_creation_id, legacy_comment_id),
  CONSTRAINT co_creation_comments_content_nonempty_chk CHECK (btrim(content) <> ''),
  CONSTRAINT co_creation_comments_status_chk CHECK (status IN ('kept', 'deleted')),
  CONSTRAINT co_creation_comments_deleted_at_chk
    CHECK (
      (status = 'kept' AND deleted_at IS NULL)
      OR (status = 'deleted' AND deleted_at IS NOT NULL AND deleted_at >= created_at)
    )
);

CREATE UNIQUE INDEX co_creation_comments_effective_account_uq
  ON app.co_creation_comments (co_creation_id, account_id)
  WHERE status = 'kept';
CREATE INDEX co_creation_comments_creation_created_idx
  ON app.co_creation_comments (co_creation_id, created_at);

CREATE TABLE app.quality_check_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_id text,
  qr_id text NOT NULL,
  operator_id bigint,
  checked_by_snapshot varchar(120) NOT NULL DEFAULT '',
  result varchar(24) NOT NULL,
  checked_at timestamptz NOT NULL,
  CONSTRAINT quality_check_logs_legacy_id_uq UNIQUE (legacy_id),
  CONSTRAINT quality_check_logs_qr_fk
    FOREIGN KEY (qr_id) REFERENCES app.qr_codes (id) ON DELETE RESTRICT,
  CONSTRAINT quality_check_logs_operator_fk
    FOREIGN KEY (operator_id) REFERENCES app.operators (id) ON DELETE RESTRICT,
  CONSTRAINT quality_check_logs_result_chk CHECK (result IN ('pass', 'bound', 'duplicate'))
);

CREATE INDEX quality_check_logs_qr_checked_idx
  ON app.quality_check_logs (qr_id, checked_at DESC);
CREATE INDEX quality_check_logs_checked_at_idx ON app.quality_check_logs (checked_at);
CREATE INDEX quality_check_logs_result_idx ON app.quality_check_logs (result);

CREATE TABLE app.products (
  id text PRIMARY KEY,
  title varchar(200) NOT NULL,
  subtitle text NOT NULL DEFAULT '',
  cover_image_url text NOT NULL DEFAULT '',
  cover_image_object_key text,
  price_text varchar(80) NOT NULL DEFAULT '',
  price_cents bigint NOT NULL,
  description text NOT NULL DEFAULT '',
  status varchar(24) NOT NULL,
  product_type varchar(32) NOT NULL,
  sticker_count integer NOT NULL DEFAULT 1,
  stock integer NOT NULL DEFAULT 0,
  is_customizable boolean NOT NULL DEFAULT false,
  shipping_note text NOT NULL DEFAULT '',
  after_sale_note text NOT NULL DEFAULT '',
  buy_type varchar(32) NOT NULL DEFAULT 'miniapp_order',
  buy_url text NOT NULL DEFAULT '',
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  CONSTRAINT products_id_nonempty_chk CHECK (btrim(id) <> ''),
  CONSTRAINT products_title_nonempty_chk CHECK (btrim(title) <> ''),
  CONSTRAINT products_price_cents_chk CHECK (price_cents >= 0),
  CONSTRAINT products_status_chk CHECK (status IN ('draft', 'published', 'hidden')),
  CONSTRAINT products_type_chk
    CHECK (product_type IN ('wine_sticker', 'sticker_set', 'custom_sticker', 'wine_gift', 'custom_wine')),
  CONSTRAINT products_sticker_count_chk CHECK (sticker_count > 0),
  CONSTRAINT products_stock_chk CHECK (stock >= 0),
  CONSTRAINT products_buy_type_chk CHECK (buy_type IN ('miniapp_order')),
  CONSTRAINT products_updated_at_chk CHECK (updated_at >= created_at)
);

CREATE INDEX products_public_sort_idx ON app.products (status, sort_order, updated_at DESC);

CREATE TABLE app.product_images (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id text NOT NULL,
  image_url text NOT NULL DEFAULT '',
  image_object_key text,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT product_images_product_fk
    FOREIGN KEY (product_id) REFERENCES app.products (id) ON DELETE CASCADE,
  CONSTRAINT product_images_locator_chk
    CHECK (btrim(image_url) <> '' OR image_object_key IS NOT NULL)
);

CREATE INDEX product_images_product_sort_idx
  ON app.product_images (product_id, sort_order, id);

CREATE TABLE app.product_scene_tags (
  product_id text NOT NULL,
  scene_key varchar(32) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (product_id, scene_key),
  CONSTRAINT product_scene_tags_product_fk
    FOREIGN KEY (product_id) REFERENCES app.products (id) ON DELETE CASCADE,
  CONSTRAINT product_scene_tags_scene_key_chk
    CHECK (scene_key IN ('lover', 'elder', 'birthday', 'wedding', 'party', 'free', 'coming_of_age'))
);

CREATE INDEX product_scene_tags_scene_key_idx ON app.product_scene_tags (scene_key);

CREATE TABLE app.orders (
  id text PRIMARY KEY,
  order_no varchar(80) NOT NULL,
  account_id varchar(32) NOT NULL,
  product_id text,
  openid_snapshot varchar(160) NOT NULL DEFAULT '',
  phone_snapshot varchar(32) NOT NULL DEFAULT '',
  product_snapshot jsonb NOT NULL,
  quantity integer NOT NULL,
  unit_price_cents bigint NOT NULL,
  total_amount_cents bigint NOT NULL,
  status varchar(24) NOT NULL,
  payment_status varchar(24) NOT NULL,
  payment_method varchar(32) NOT NULL DEFAULT '',
  payment_mock boolean NOT NULL DEFAULT false,
  provider_transaction_id varchar(160),
  provider_transaction_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  paid_at timestamptz,
  receiver_name varchar(120) NOT NULL,
  receiver_phone varchar(32) NOT NULL,
  region varchar(240) NOT NULL,
  address text NOT NULL,
  remark text NOT NULL DEFAULT '',
  express_company varchar(120) NOT NULL DEFAULT '',
  express_no varchar(160) NOT NULL DEFAULT '',
  shipped_at timestamptz,
  refund_status varchar(32) NOT NULL DEFAULT '',
  admin_note text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  CONSTRAINT orders_order_no_uq UNIQUE (order_no),
  CONSTRAINT orders_account_fk
    FOREIGN KEY (account_id) REFERENCES app.accounts (id) ON DELETE RESTRICT,
  CONSTRAINT orders_product_fk
    FOREIGN KEY (product_id) REFERENCES app.products (id) ON DELETE RESTRICT,
  CONSTRAINT orders_quantity_chk CHECK (quantity > 0),
  CONSTRAINT orders_unit_price_cents_chk CHECK (unit_price_cents >= 0),
  CONSTRAINT orders_total_amount_cents_chk CHECK (total_amount_cents >= 0),
  CONSTRAINT orders_total_recomputes_chk CHECK (total_amount_cents = unit_price_cents * quantity),
  CONSTRAINT orders_status_chk
    CHECK (status IN ('pending_payment', 'paid', 'shipped', 'completed', 'cancelled', 'refunding', 'refunded')),
  CONSTRAINT orders_payment_status_chk
    CHECK (payment_status IN ('unpaid', 'paid', 'failed', 'refunded')),
  CONSTRAINT orders_updated_at_chk CHECK (updated_at >= created_at),
  CONSTRAINT orders_paid_at_chk CHECK (paid_at IS NULL OR paid_at >= created_at),
  CONSTRAINT orders_shipped_at_chk CHECK (shipped_at IS NULL OR shipped_at >= created_at)
);

CREATE INDEX orders_account_created_idx ON app.orders (account_id, created_at DESC);
CREATE INDEX orders_status_created_idx ON app.orders (status, created_at DESC);
CREATE INDEX orders_payment_status_idx ON app.orders (payment_status);
CREATE INDEX orders_provider_transaction_idx
  ON app.orders (provider_transaction_id) WHERE provider_transaction_id IS NOT NULL;

CREATE TABLE app.payment_transactions (
  id uuid PRIMARY KEY,
  order_id text NOT NULL,
  provider varchar(32) NOT NULL,
  merchant_order_no varchar(80) NOT NULL,
  provider_transaction_id varchar(160),
  amount_cents bigint NOT NULL,
  status varchar(24) NOT NULL,
  paid_at timestamptz,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  CONSTRAINT payment_transactions_order_fk
    FOREIGN KEY (order_id) REFERENCES app.orders (id) ON DELETE RESTRICT,
  CONSTRAINT payment_transactions_provider_merchant_uq
    UNIQUE (provider, merchant_order_no),
  CONSTRAINT payment_transactions_amount_cents_chk CHECK (amount_cents >= 0),
  CONSTRAINT payment_transactions_status_chk
    CHECK (status IN ('created', 'pending', 'paid', 'failed', 'closed', 'refunded')),
  CONSTRAINT payment_transactions_updated_at_chk CHECK (updated_at >= created_at),
  CONSTRAINT payment_transactions_paid_at_chk CHECK (paid_at IS NULL OR paid_at >= created_at)
);

CREATE UNIQUE INDEX payment_transactions_provider_transaction_uq
  ON app.payment_transactions (provider, provider_transaction_id)
  WHERE provider_transaction_id IS NOT NULL;
CREATE INDEX payment_transactions_order_created_idx
  ON app.payment_transactions (order_id, created_at DESC);
CREATE INDEX payment_transactions_status_idx ON app.payment_transactions (status);

CREATE TABLE app.payment_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_id text,
  payment_transaction_id uuid,
  order_id text,
  event_type varchar(80) NOT NULL,
  status varchar(32) NOT NULL,
  payload_sha256 char(64),
  sanitized_metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL,
  CONSTRAINT payment_events_legacy_id_uq UNIQUE (legacy_id),
  CONSTRAINT payment_events_transaction_fk
    FOREIGN KEY (payment_transaction_id) REFERENCES app.payment_transactions (id) ON DELETE RESTRICT,
  CONSTRAINT payment_events_order_fk
    FOREIGN KEY (order_id) REFERENCES app.orders (id) ON DELETE RESTRICT,
  CONSTRAINT payment_events_relation_chk
    CHECK (payment_transaction_id IS NOT NULL OR order_id IS NOT NULL),
  CONSTRAINT payment_events_payload_sha256_format_chk
    CHECK (payload_sha256 IS NULL OR payload_sha256 ~ '^[0-9a-f]{64}$')
);

CREATE INDEX payment_events_transaction_created_idx
  ON app.payment_events (payment_transaction_id, created_at DESC);
CREATE INDEX payment_events_order_created_idx
  ON app.payment_events (order_id, created_at DESC);

CREATE TABLE app.record_proofs (
  id uuid PRIMARY KEY,
  record_qr_id text NOT NULL,
  provider varchar(64) NOT NULL,
  status varchar(32) NOT NULL,
  operation_id varchar(200),
  manifest_object_key text,
  manifest_hash char(64),
  transaction_hash varchar(255),
  block_height bigint,
  provider_record_id varchar(200),
  provider_certificate_url text,
  certificate_object_key text,
  certificate_object_url_snapshot text,
  confirmed_at timestamptz,
  callback_received_at timestamptz,
  retry_count integer NOT NULL DEFAULT 0,
  last_error text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  CONSTRAINT record_proofs_record_provider_uq UNIQUE (record_qr_id, provider),
  CONSTRAINT record_proofs_record_fk
    FOREIGN KEY (record_qr_id) REFERENCES app.records (qr_id) ON DELETE RESTRICT,
  CONSTRAINT record_proofs_status_chk
    CHECK (status IN ('not_started', 'manifest_ready', 'submitting', 'submitted', 'confirmed', 'failed', 'retrying')),
  CONSTRAINT record_proofs_manifest_hash_format_chk
    CHECK (manifest_hash IS NULL OR manifest_hash ~ '^[0-9a-f]{64}$'),
  CONSTRAINT record_proofs_block_height_chk CHECK (block_height IS NULL OR block_height >= 0),
  CONSTRAINT record_proofs_retry_count_chk CHECK (retry_count >= 0),
  CONSTRAINT record_proofs_updated_at_chk CHECK (updated_at >= created_at)
);

CREATE UNIQUE INDEX record_proofs_provider_operation_uq
  ON app.record_proofs (provider, operation_id) WHERE operation_id IS NOT NULL;
CREATE INDEX record_proofs_operation_id_idx
  ON app.record_proofs (operation_id) WHERE operation_id IS NOT NULL;
CREATE INDEX record_proofs_status_idx ON app.record_proofs (status);

CREATE TABLE app.proof_attempts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  proof_id uuid NOT NULL,
  attempt_number integer NOT NULL,
  request_state varchar(32) NOT NULL,
  result_status varchar(32) NOT NULL,
  sanitized_error text NOT NULL DEFAULT '',
  requested_at timestamptz NOT NULL,
  completed_at timestamptz,
  CONSTRAINT proof_attempts_proof_attempt_uq UNIQUE (proof_id, attempt_number),
  CONSTRAINT proof_attempts_proof_fk
    FOREIGN KEY (proof_id) REFERENCES app.record_proofs (id) ON DELETE RESTRICT,
  CONSTRAINT proof_attempts_attempt_number_chk CHECK (attempt_number > 0),
  CONSTRAINT proof_attempts_request_state_chk
    CHECK (request_state IN ('queued', 'started', 'sent')),
  CONSTRAINT proof_attempts_result_status_chk
    CHECK (result_status IN ('pending', 'succeeded', 'failed')),
  CONSTRAINT proof_attempts_completed_at_chk
    CHECK (completed_at IS NULL OR completed_at >= requested_at)
);

CREATE INDEX proof_attempts_proof_requested_idx
  ON app.proof_attempts (proof_id, requested_at DESC);

CREATE TABLE app.record_archives (
  record_qr_id text PRIMARY KEY,
  manifest_object_key text,
  legacy_manifest_object_key text,
  index_object_key text,
  status varchar(24) NOT NULL,
  last_error text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  CONSTRAINT record_archives_record_fk
    FOREIGN KEY (record_qr_id) REFERENCES app.records (qr_id) ON DELETE RESTRICT,
  CONSTRAINT record_archives_status_chk
    CHECK (status IN ('not_started', 'pending', 'ready', 'failed')),
  CONSTRAINT record_archives_updated_at_chk CHECK (updated_at >= created_at)
);

CREATE INDEX record_archives_status_idx ON app.record_archives (status);

CREATE TABLE app.miniapp_content (
  id smallint PRIMARY KEY,
  home_title varchar(240) NOT NULL,
  home_subtitle text NOT NULL,
  logo_image text NOT NULL DEFAULT '',
  home_banner_image text NOT NULL DEFAULT '',
  home_slides jsonb NOT NULL DEFAULT '[]'::jsonb,
  scene_cards jsonb NOT NULL DEFAULT '[]'::jsonb,
  project_title varchar(240) NOT NULL,
  project_body text NOT NULL,
  brand_story_title varchar(240) NOT NULL,
  brand_story_body text NOT NULL,
  consult_label varchar(120) NOT NULL,
  consult_url text NOT NULL DEFAULT '',
  share_title varchar(240) NOT NULL,
  share_description text NOT NULL,
  updated_by_operator_id bigint,
  updated_by_snapshot varchar(120) NOT NULL DEFAULT '',
  updated_at timestamptz NOT NULL,
  CONSTRAINT miniapp_content_singleton_chk CHECK (id = 1),
  CONSTRAINT miniapp_content_operator_fk
    FOREIGN KEY (updated_by_operator_id) REFERENCES app.operators (id) ON DELETE RESTRICT,
  CONSTRAINT miniapp_content_slides_array_chk
    CHECK (jsonb_typeof(home_slides) = 'array'),
  CONSTRAINT miniapp_content_scene_cards_array_chk
    CHECK (jsonb_typeof(scene_cards) = 'array')
);

CREATE TABLE app.audit_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_type varchar(32) NOT NULL,
  actor_reference varchar(160),
  actor_reference_hash char(64),
  action varchar(120) NOT NULL,
  entity_type varchar(80) NOT NULL,
  entity_id varchar(200),
  entity_reference_hash char(64),
  request_method varchar(16),
  request_path varchar(240),
  result_status varchar(32) NOT NULL,
  ip_hash varchar(64),
  user_agent_family varchar(120),
  duration_ms integer,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT audit_events_actor_type_chk
    CHECK (actor_type IN ('system', 'account', 'operator', 'external')),
  CONSTRAINT audit_events_result_status_chk
    CHECK (result_status IN ('success', 'denied', 'failed')),
  CONSTRAINT audit_events_actor_reference_hash_format_chk
    CHECK (actor_reference_hash IS NULL OR actor_reference_hash ~ '^[0-9a-f]{64}$'),
  CONSTRAINT audit_events_entity_reference_hash_format_chk
    CHECK (entity_reference_hash IS NULL OR entity_reference_hash ~ '^[0-9a-f]{64}$'),
  CONSTRAINT audit_events_duration_ms_chk CHECK (duration_ms IS NULL OR duration_ms >= 0),
  CONSTRAINT audit_events_entity_reference_chk
    CHECK (entity_id IS NOT NULL OR entity_reference_hash IS NOT NULL)
);

CREATE INDEX audit_events_entity_created_idx
  ON app.audit_events (entity_type, entity_id, created_at DESC);
CREATE INDEX audit_events_action_created_idx ON app.audit_events (action, created_at DESC);

CREATE TABLE app.outbox_jobs (
  id uuid PRIMARY KEY,
  job_type varchar(80) NOT NULL,
  aggregate_type varchar(80) NOT NULL,
  aggregate_id varchar(200) NOT NULL,
  idempotency_key varchar(240) NOT NULL,
  payload jsonb NOT NULL,
  status varchar(24) NOT NULL,
  attempt_count integer NOT NULL DEFAULT 0,
  available_at timestamptz NOT NULL,
  locked_at timestamptz,
  locked_by varchar(160),
  last_error text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  CONSTRAINT outbox_jobs_idempotency_key_uq UNIQUE (idempotency_key),
  CONSTRAINT outbox_jobs_status_chk
    CHECK (status IN ('pending', 'processing', 'succeeded', 'failed')),
  CONSTRAINT outbox_jobs_attempt_count_chk CHECK (attempt_count >= 0),
  CONSTRAINT outbox_jobs_lock_pair_chk
    CHECK ((locked_at IS NULL AND locked_by IS NULL) OR (locked_at IS NOT NULL AND locked_by IS NOT NULL)),
  CONSTRAINT outbox_jobs_updated_at_chk CHECK (updated_at >= created_at)
);

CREATE INDEX outbox_jobs_status_available_idx
  ON app.outbox_jobs (status, available_at, created_at);
CREATE INDEX outbox_jobs_aggregate_idx
  ON app.outbox_jobs (aggregate_type, aggregate_id, created_at DESC);
