#!/usr/bin/env bash
set -Eeuo pipefail
umask 077

REPO=/www/wwwroot/xingxingzaishan
LOCK_FILE=/run/lock/xingxingzaishan-stable-cutover-prewrite.lock
STATE_ROOT=/root/stable-cutover-prewrite-audit-20260812

fail() {
  echo "STABLE_CUTOVER_PREWRITE_AUTO_OFF=BLOCKED_$1" >&2
  exit 1
}

runtime_value() {
  local app_pid="$1"
  local key="$2"
  tr '\0' '\n' < "/proc/$app_pid/environ" |
    sed -n "s/^${key}=//p" |
    tail -n 1
}

wait_for_http() {
  local code=''
  for _attempt in $(seq 1 20); do
    code="$(curl -sS -o /dev/null -w '%{http_code}' \
      --connect-timeout 2 --max-time 3 \
      http://127.0.0.1:3000/ 2>/dev/null || true)"
    [ "$code" = 200 ] && {
      printf '%s\n' "$code"
      return 0
    }
    sleep 1
  done
  return 1
}

postgres_boundary_count() {
  local app_pid="$1"
  local count=0 flag
  for flag in \
    PUBLIC_QR_POSTGRES_READ_ENABLED \
    PERSONAL_RECORD_POSTGRES_READ_ENABLED \
    QR_LIFECYCLE_POSTGRES_WRITE_ENABLED \
    IDENTITY_POSTGRES_AUTHORITY_ENABLED \
    QR_ISSUANCE_POSTGRES_AUTHORITY_ENABLED
  do
    [ "$(runtime_value "$app_pid" "$flag")" = true ] && count=$((count + 1))
  done
  printf '%s\n' "$count"
}

assert_boundaries_off() {
  local app_pid="$1"
  local flag value
  for flag in \
    PUBLIC_QR_POSTGRES_READ_ENABLED \
    PERSONAL_RECORD_POSTGRES_READ_ENABLED \
    QR_LIFECYCLE_POSTGRES_WRITE_ENABLED \
    IDENTITY_POSTGRES_AUTHORITY_ENABLED \
    QR_ISSUANCE_POSTGRES_AUTHORITY_ENABLED \
    RECORD_PROOF_RUNTIME_ENABLED
  do
    value="$(runtime_value "$app_pid" "$flag")"
    [ -z "$value" ] || [ "$value" = false ] || return 1
  done
}

assert_no_runtime_secret() {
  local app_pid="$1"
  ! tr '\0' '\n' < "/proc/$app_pid/environ" |
    grep -Eq '^(DATABASE_URL|PGPASSWORD|AVATA_API_KEY|AVATA_API_SECRET)=.+$'
}

STATE_FILE=''
AUTOMATIC=false
for ARG in "$@"; do
  case "$ARG" in
    --state=*) STATE_FILE="${ARG#--state=}" ;;
    --automatic=true) AUTOMATIC=true ;;
    --automatic=false) AUTOMATIC=false ;;
    *) fail ARGUMENT_INVALID ;;
  esac
done
[ "$#" -eq 2 ] || fail ARGUMENT_COUNT_INVALID
[ "$(id -u)" -eq 0 ] || fail ROOT_REQUIRED
case "$STATE_FILE" in
  "$STATE_ROOT"/*/prewrite-state.env) ;;
  *) fail STATE_PATH_INVALID ;;
esac
[ -f "$STATE_FILE" ] && [ ! -L "$STATE_FILE" ] || fail STATE_FILE_INVALID
[ "$(stat -c '%U:%G' "$STATE_FILE")" = root:root ] || fail STATE_OWNER_INVALID
[ "$(stat -c '%a' "$STATE_FILE")" = 600 ] || fail STATE_MODE_INVALID
if grep -Ev '^[A-Z][A-Z0-9_]*=[A-Za-z0-9_./:+-]+$' "$STATE_FILE" |
   grep -q .; then
  fail STATE_CONTENT_INVALID
fi

# Generated by the root-only prewrite runner after strict key/value validation.
. "$STATE_FILE"
[ "${STATE_VERSION:-}" = 1 ] || fail STATE_VERSION_INVALID
if [ "${PHASE:-}" = JSON_AUTHORITY_ABORTED ]; then
  echo 'STABLE_CUTOVER_PREWRITE_AUTO_OFF=ALREADY_ABORTED'
  exit 0
fi
[ "${PHASE:-}" = POSTGRES_AUTHORITY_PREWRITE ] || fail STATE_PHASE_INVALID
[ "${AUTHORITY_COMMIT_POINT_CROSSED:-}" = NO ] || fail COMMIT_POINT_CROSSED
[ "${APP_NAME:-}" = xingxingzaishan ] || fail APP_NAME_INVALID
[ "${CANDIDATE_DATABASE:-}" = xingxing_clean_baseline_20260812_staging ] || \
  fail CANDIDATE_DATABASE_INVALID
[ "${EXPECTED_JSON_SHA256:-}" = \
  f263df13b5c19f91b0f86d93960f6b26896f3ed605318c73dd8546d110b06cfd ] || \
  fail JSON_HASH_INVALID
[[ "${EXPECTED_BASELINE_DOMAIN_SHA256:-}" =~ ^[a-f0-9]{64}$ ]] || \
  fail BASELINE_DOMAIN_HASH_INVALID
[ -f "${CANDIDATE_ENVIRONMENT:-}" ] && [ ! -L "$CANDIDATE_ENVIRONMENT" ] || \
  fail CANDIDATE_ENV_INVALID
[ "$(stat -c '%U:%G' "$CANDIDATE_ENVIRONMENT")" = root:root ] || \
  fail CANDIDATE_ENV_OWNER_INVALID
[ "$(stat -c '%a' "$CANDIDATE_ENVIRONMENT")" = 600 ] || \
  fail CANDIDATE_ENV_MODE_INVALID
[ "$(sha256sum "$CANDIDATE_ENVIRONMENT" | awk '{print $1}')" = \
  "${CANDIDATE_ENVIRONMENT_SHA256:-}" ] || fail CANDIDATE_ENV_CHANGED
EXPECTED_AUTO_OFF_SCRIPT="$(dirname "$STATE_FILE")/prewrite-auto-off.sh"
[ "$(readlink -f "$0")" = "$EXPECTED_AUTO_OFF_SCRIPT" ] || \
  fail AUTO_OFF_SCRIPT_PATH_INVALID
[ -f "$EXPECTED_AUTO_OFF_SCRIPT" ] && [ ! -L "$EXPECTED_AUTO_OFF_SCRIPT" ] || \
  fail AUTO_OFF_SCRIPT_INVALID
[ "$(stat -c '%U:%G' "$EXPECTED_AUTO_OFF_SCRIPT")" = root:root ] || \
  fail AUTO_OFF_SCRIPT_OWNER_INVALID
[ "$(stat -c '%a' "$EXPECTED_AUTO_OFF_SCRIPT")" = 700 ] || \
  fail AUTO_OFF_SCRIPT_MODE_INVALID
[ "$(sha256sum "$EXPECTED_AUTO_OFF_SCRIPT" | awk '{print $1}')" = \
  "${AUTO_OFF_SCRIPT_SHA256:-}" ] || fail AUTO_OFF_SCRIPT_HASH_INVALID

command -v flock >/dev/null 2>&1 || fail FLOCK_REQUIRED
command -v pm2 >/dev/null 2>&1 || fail PM2_REQUIRED
command -v curl >/dev/null 2>&1 || fail CURL_REQUIRED
exec 9>"$LOCK_FILE"
flock -n 9 || fail CUTOVER_OPERATION_ALREADY_RUNNING

cd "$REPO"
[ "$(git rev-parse HEAD)" = "${EXPECTED_HEAD:-}" ] || fail HEAD_CHANGED
[ "$(git rev-parse 'HEAD^{tree}')" = "${EXPECTED_TREE:-}" ] || fail TREE_CHANGED
[ "$(sha256sum src/server/data/db.json | awk '{print $1}')" = \
  "$EXPECTED_JSON_SHA256" ] || fail LIVE_JSON_CHANGED

unset DATABASE_URL PGHOST PGPORT PGUSER PGPASSWORD PGDATABASE
unset PGSSL PGSSLMODE PGOPTIONS PGAPPLICATION_NAME
set -a
. "$CANDIDATE_ENVIRONMENT"
set +a
[ "$PGDATABASE" = "$CANDIDATE_DATABASE" ] || fail CANDIDATE_ENV_DATABASE_INVALID
export PGOPTIONS='-c default_transaction_read_only=on -c statement_timeout=15000ms'
export PGAPPLICATION_NAME=xingxingzaishan-prewrite-auto-off-gate
CANDIDATE_STATE="$(
  /usr/pgsql-15/bin/psql -X -At -F '|' -v ON_ERROR_STOP=1 \
    -c "SELECT
          (SELECT count(*) FROM app.qr_codes),
          (SELECT count(*) FROM app.records),
          (SELECT count(*) FROM app.import_runs WHERE status = 'passed'),
          (SELECT count(*) FROM app.import_runs WHERE status <> 'passed'),
          (SELECT count(*) FROM app.outbox_jobs),
          (SELECT checksum_summary->>'source_sha256' FROM app.import_runs
            WHERE status = 'passed' ORDER BY completed_at DESC LIMIT 1),
          (SELECT checksum_summary->>'plan_sha256' FROM app.import_runs
            WHERE status = 'passed' ORDER BY completed_at DESC LIMIT 1),
          (SELECT checksum_summary->>'public_qr_v1_sha256' FROM app.import_runs
            WHERE status = 'passed' ORDER BY completed_at DESC LIMIT 1);"
)"
unset DATABASE_URL PGHOST PGPORT PGUSER PGPASSWORD PGDATABASE
unset PGSSL PGSSLMODE PGOPTIONS PGAPPLICATION_NAME
[ "$(printf '%s' "$CANDIDATE_STATE" | sha256sum | awk '{print $1}')" = \
  "${EXPECTED_DATABASE_STATE_SHA256:-}" ] || \
  fail CANDIDATE_MUTATION_DETECTED_KEEP_POSTGRES_FROZEN

APP_PID_BEFORE="$(pm2 pid "$APP_NAME" | tail -n 1)"
[ -n "$APP_PID_BEFORE" ] && [ "$APP_PID_BEFORE" != 0 ] || fail APP_PID_MISSING
BOUNDARY_COUNT="$(postgres_boundary_count "$APP_PID_BEFORE")"
FREEZE_STATE="$(runtime_value "$APP_PID_BEFORE" POSTGRES_CUTOVER_WRITE_FREEZE_ENABLED)"

if [ "$BOUNDARY_COUNT" = 5 ] && [ "$FREEZE_STATE" = true ]; then
  RUNTIME_STATE=POSTGRES_AUTHORITY_PREWRITE
elif [ "$BOUNDARY_COUNT" = 0 ] && [ "$FREEZE_STATE" = true ] &&
     assert_boundaries_off "$APP_PID_BEFORE" &&
     assert_no_runtime_secret "$APP_PID_BEFORE"; then
  RUNTIME_STATE=JSON_AUTHORITY_FROZEN
elif [ "$BOUNDARY_COUNT" = 0 ] &&
     { [ -z "$FREEZE_STATE" ] || [ "$FREEZE_STATE" = false ]; } &&
     assert_boundaries_off "$APP_PID_BEFORE" &&
     assert_no_runtime_secret "$APP_PID_BEFORE"; then
  RUNTIME_STATE=JSON_AUTHORITY
else
  RUNTIME_STATE=PARTIAL_RUNTIME_RECOVERY
fi

if [ "$AUTOMATIC" = false ] && [ -n "${AUTO_OFF_UNIT:-}" ]; then
  systemctl stop "${AUTO_OFF_UNIT}.timer" >/dev/null 2>&1 || true
fi

APP_PID_FROZEN="$APP_PID_BEFORE"
if [ "$RUNTIME_STATE" = POSTGRES_AUTHORITY_PREWRITE ] ||
   [ "$RUNTIME_STATE" = PARTIAL_RUNTIME_RECOVERY ]; then
  export PUBLIC_QR_SHADOW_READ_ENABLED=false
  export PERSONAL_RECORD_SHADOW_READ_ENABLED=false
  export IDENTITY_SHADOW_READ_ENABLED=false
  export PUBLIC_QR_POSTGRES_READ_ENABLED=false
  export PERSONAL_RECORD_POSTGRES_READ_ENABLED=false
  export QR_LIFECYCLE_POSTGRES_WRITE_ENABLED=false
  export IDENTITY_POSTGRES_AUTHORITY_ENABLED=false
  export QR_ISSUANCE_POSTGRES_AUTHORITY_ENABLED=false
  export RECORD_PROOF_RUNTIME_ENABLED=false
  export POSTGRES_CUTOVER_WRITE_FREEZE_ENABLED=true
  export PUBLIC_QR_POSTGRES_READ_SCOPE=''
  export PUBLIC_QR_POSTGRES_READ_ALLOWLIST=''
  export PUBLIC_QR_POSTGRES_READ_DOMAIN_SHA256=''
  export PERSONAL_RECORD_POSTGRES_READ_SCOPE=''
  export PERSONAL_RECORD_POSTGRES_READ_ALLOWLIST=''
  export PERSONAL_RECORD_POSTGRES_READ_DOMAIN_SHA256=''
  export QR_LIFECYCLE_POSTGRES_WRITE_SCOPE=''
  export QR_LIFECYCLE_POSTGRES_WRITE_ALLOWLIST=''
  export QR_LIFECYCLE_POSTGRES_WRITE_DOMAIN_SHA256=''
  export POSTGRES_AUTHORITY_BASELINE_DOMAIN_SHA256=''
  export IDENTITY_POSTGRES_AUTHORITY_SCOPE=''
  export IDENTITY_POSTGRES_AUTHORITY_ALLOWLIST=''
  export IDENTITY_POSTGRES_AUTHORITY_SOURCE_SHA256=''
  export IDENTITY_POSTGRES_AUTHORITY_DOMAIN_SHA256=''
  export QR_ISSUANCE_POSTGRES_AUTHORITY_SCOPE=''
  export QR_ISSUANCE_POSTGRES_AUTHORITY_ALLOWLIST=''
  export QR_ISSUANCE_POSTGRES_AUTHORITY_SOURCE_SHA256=''
  export QR_ISSUANCE_POSTGRES_AUTHORITY_DOMAIN_SHA256=''
  export DATABASE_URL=''
  export PGHOST=''
  export PGPORT=''
  export PGUSER=''
  export PGPASSWORD=''
  export PGDATABASE=''
  export PGSSL=''
  export PGAPPLICATION_NAME=''
  export AVATA_API_KEY=''
  export AVATA_API_SECRET=''
  export AVATA_IDENTITY_NAME=''
  export AVATA_IDENTITY_NUM=''
  export AVATA_API_BASE=''
  export AVATA_ENV=''
  export CHAIN_ENABLED=false
  export CHAIN_CALLBACK_URL=''

  pm2 restart "$APP_NAME" --update-env
  APP_PID_FROZEN="$(pm2 pid "$APP_NAME" | tail -n 1)"
  [ -n "$APP_PID_FROZEN" ] && [ "$APP_PID_FROZEN" != 0 ] || \
    fail FROZEN_PID_MISSING
  [ "$APP_PID_FROZEN" != "$APP_PID_BEFORE" ] || fail FROZEN_PID_NOT_REPLACED
  wait_for_http >/dev/null || fail JSON_FROZEN_HTTP_INVALID
fi

if [ "$RUNTIME_STATE" != JSON_AUTHORITY ]; then
  assert_boundaries_off "$APP_PID_FROZEN" || fail JSON_FROZEN_BOUNDARY_ACTIVE
  assert_no_runtime_secret "$APP_PID_FROZEN" || fail JSON_FROZEN_SECRET_PRESENT
  [ "$(runtime_value "$APP_PID_FROZEN" POSTGRES_CUTOVER_WRITE_FREEZE_ENABLED)" = \
    true ] || fail JSON_FROZEN_WRITE_FREEZE_NOT_ACTIVE
  if ss -tnp | grep ':5432' | grep -Fq "pid=$APP_PID_FROZEN,"; then
    fail JSON_FROZEN_POSTGRES_CONNECTION_PRESENT
  fi

  FROZEN_RESPONSE="$(dirname "$STATE_FILE")/auto-off-frozen-response.json"
  if [ ! -e "$FROZEN_RESPONSE" ]; then
    FROZEN_POST_CODE="$(curl -sS -o "$FROZEN_RESPONSE" -w '%{http_code}' \
      -H 'Content-Type: application/json' --data '{}' \
      --connect-timeout 5 --max-time 10 \
      http://127.0.0.1:3000/api/user/login)"
    chmod 0600 "$FROZEN_RESPONSE"
    [ "$FROZEN_POST_CODE" = 503 ] || fail JSON_FROZEN_POST_NOT_BLOCKED
    grep -Fq 'POSTGRES_CUTOVER_WRITE_FROZEN' "$FROZEN_RESPONSE" || \
      fail JSON_FROZEN_RESPONSE_INVALID
  fi

  export POSTGRES_CUTOVER_WRITE_FREEZE_ENABLED=false
  pm2 restart "$APP_NAME" --update-env
  APP_PID_FINAL="$(pm2 pid "$APP_NAME" | tail -n 1)"
  [ -n "$APP_PID_FINAL" ] && [ "$APP_PID_FINAL" != 0 ] || fail FINAL_PID_MISSING
  [ "$APP_PID_FINAL" != "$APP_PID_FROZEN" ] || fail FINAL_PID_NOT_REPLACED
else
  APP_PID_FINAL="$APP_PID_BEFORE"
fi

HTTP_CODE="$(wait_for_http)" || fail JSON_AUTHORITY_HTTP_INVALID
UNFROZEN_RESPONSE="$(dirname "$STATE_FILE")/auto-off-unfrozen-response.json"
if [ ! -e "$UNFROZEN_RESPONSE" ]; then
  UNFROZEN_POST_CODE="$(curl -sS -o "$UNFROZEN_RESPONSE" -w '%{http_code}' \
    -H 'Content-Type: application/json' --data '{}' \
    --connect-timeout 5 --max-time 10 \
    http://127.0.0.1:3000/api/user/login)"
  chmod 0600 "$UNFROZEN_RESPONSE"
  [ "$UNFROZEN_POST_CODE" != 503 ] || fail JSON_AUTHORITY_STILL_FROZEN
fi

assert_boundaries_off "$APP_PID_FINAL" || fail FINAL_POSTGRES_BOUNDARY_NOT_OFF
FINAL_FREEZE_STATE="$(
  runtime_value "$APP_PID_FINAL" POSTGRES_CUTOVER_WRITE_FREEZE_ENABLED
)"
if [ "$RUNTIME_STATE" = JSON_AUTHORITY ]; then
  [ -z "$FINAL_FREEZE_STATE" ] || [ "$FINAL_FREEZE_STATE" = false ] || \
    fail FINAL_WRITE_FREEZE_NOT_OFF
else
  [ "$FINAL_FREEZE_STATE" = false ] || fail FINAL_WRITE_FREEZE_NOT_OFF
fi
assert_no_runtime_secret "$APP_PID_FINAL" || fail FINAL_SECRET_STATE_INVALID
if ss -tnp | grep ':5432' | grep -Fq "pid=$APP_PID_FINAL,"; then
  fail FINAL_POSTGRES_CONNECTION_PRESENT
fi
[ "$(sha256sum src/server/data/db.json | awk '{print $1}')" = \
  "$EXPECTED_JSON_SHA256" ] || fail FINAL_JSON_CHANGED

STATE_TEMP="${STATE_FILE}.tmp.$$"
awk -F= '
  BEGIN { phase = 0; point = 0 }
  $1 == "PHASE" { print "PHASE=JSON_AUTHORITY_ABORTED"; phase = 1; next }
  $1 == "AUTHORITY_COMMIT_POINT_CROSSED" {
    print "AUTHORITY_COMMIT_POINT_CROSSED=NO"; point = 1; next
  }
  { print }
  END {
    if (!phase) print "PHASE=JSON_AUTHORITY_ABORTED"
    if (!point) print "AUTHORITY_COMMIT_POINT_CROSSED=NO"
  }
' "$STATE_FILE" > "$STATE_TEMP"
printf '%s\n' \
  "ABORTED_AT_UTC=$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
  "ABORT_MODE=$([ "$AUTOMATIC" = true ] && echo AUTOMATIC || echo MANUAL)" \
  >> "$STATE_TEMP"
chmod 0600 "$STATE_TEMP"
mv -f "$STATE_TEMP" "$STATE_FILE"

SUMMARY="$(dirname "$STATE_FILE")/auto-off-summary.txt"
if [ ! -e "$SUMMARY" ]; then
  install -o root -g root -m 0600 /dev/null "$SUMMARY"
  printf '%s\n' \
    'STABLE_CUTOVER_PREWRITE_AUTO_OFF=PASS' \
    'FINAL_STATE=JSON_AUTHORITY' \
    'CANDIDATE_DATABASE_MUTATION=NONE' \
    'AUTHORITY_COMMIT_POINT_CROSSED=NO' \
    'POSTGRES_AUTHORITY_BOUNDARIES_ENABLED=0' \
    'POSTGRES_CUTOVER_WRITE_FREEZE_ENABLED=false' \
    'RECORD_PROOF_RUNTIME_ENABLED=false' \
    'AVATA_CONFIGURATION_LOADED=NO' \
    'PM2_CONFIGURATION_SAVED=NO' \
    'FINAL_POSTGRES_CONNECTION=NONE' \
    "ENTRY_RUNTIME_STATE=$RUNTIME_STATE" \
    "FINAL_APP_PID=$APP_PID_FINAL" \
    "FINAL_APP_HTTP=$HTTP_CODE" \
    "COMPLETED_AT_UTC=$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
    > "$SUMMARY"
fi

stat -c 'OWNER=%U:%G MODE=%a SIZE=%s PATH=%n' "$STATE_FILE" "$SUMMARY"
echo "ENTRY_RUNTIME_STATE=$RUNTIME_STATE"
echo "APP_PID_BEFORE=$APP_PID_BEFORE"
echo "APP_PID_FROZEN=$APP_PID_FROZEN"
echo "APP_PID_FINAL=$APP_PID_FINAL"
echo "APP_HTTP=$HTTP_CODE"
echo 'STABLE_CUTOVER_PREWRITE_AUTO_OFF=PASS'
echo 'FINAL_STATE=JSON_AUTHORITY'
echo 'CANDIDATE_DATABASE_MUTATION=NONE'
echo 'AUTHORITY_COMMIT_POINT_CROSSED=NO'
echo 'PM2_CONFIGURATION_SAVED=NO'
echo 'FINAL_POSTGRES_CONNECTION=NONE'
